services:
  - type: web
    name: kouka-battle
    env: node
    rootDir: kouka_battle
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.19.0

